// 自定义引擎（Custom Engine）：用户定义的任意搜索引擎，URL 模板含 %s 占位符。
//
// 与 site-engines.ts 同构：纯函数、无浏览器 API、防御式规范化。
// 区别：site-engine 把 site: 前缀注入已有引擎，custom-engine 直接导航到用户指定的 URL。

/** IDs for user-defined custom search engines. */
export type CustomEngineId = `custom:${string}`;

/** Persisted Custom Engine record. `urlTemplate` must contain exactly one `%s`. */
export interface CustomEngineDefinition {
  id: CustomEngineId;
  name: string;
  urlTemplate: string;
}

const CUSTOM_ID_PREFIX = 'custom:';
/** Stable, storage-safe ids generated by the worker (UUIDs satisfy this form). */
const CUSTOM_ID_TOKEN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;

export const MAX_CUSTOM_ENGINES = 50;
export const MAX_CUSTOM_ENGINE_NAME_LENGTH = 40;
export const MAX_CUSTOM_ENGINE_URL_LENGTH = 2048;
// Leaves ample room below the 256 KiB complete-import limit for the rest of the
// config while still bounding a persisted collection read from storage.
export const MAX_CUSTOM_ENGINES_SERIALIZED_BYTES = 128 * 1024;

export function isCustomEngineId(id: string): id is CustomEngineId {
  return id.startsWith(CUSTOM_ID_PREFIX) && CUSTOM_ID_TOKEN.test(id.slice(CUSTOM_ID_PREFIX.length));
}

/**
 * Validates and canonicalizes a URL template string.
 * Must be a valid http(s) URL containing exactly one lowercase `%s` placeholder.
 * Rejects credentials and internal whitespace (mirrors site-engines normalizeSiteTarget).
 * Returns the canonical form (scheme+host lowercased) or null.
 */
export function normalizeCustomEngineUrlTemplate(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const input = value.trim();
  if (!input || input.length > MAX_CUSTOM_ENGINE_URL_LENGTH) return null;
  // Reject internal whitespace (same as site-engines).
  if (/\s/.test(input)) return null;

  // Must contain exactly one lowercase %s
  const matches = input.match(/%s/g);
  if (!matches || matches.length !== 1) return null;

  // Parse with a sentinel so the URL serializer does not percent-encode the placeholder.
  const SENTINEL = 'JUSOQUERYPLACEHOLDER';
  let url: URL;
  try {
    url = new URL(input.replace('%s', SENTINEL));
  } catch {
    return null;
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
  // Reject credentials (mirrors site-engines.ts:77).
  if (url.username || url.password) return null;

  // Canonicalize: url.href has scheme+host lowercased by the URL serializer.
  const canonical = url.href.replace(SENTINEL, '%s');
  if (canonical.length > MAX_CUSTOM_ENGINE_URL_LENGTH) return null;
  return canonical;
}

/** Validates and canonicalizes an untrusted persisted Custom Engine record. */
export function normalizeCustomEngineDefinition(value: unknown): CustomEngineDefinition | null {
  if (!value || typeof value !== 'object') return null;
  const candidate = value as Record<string, unknown>;
  if (typeof candidate.id !== 'string' || !isCustomEngineId(candidate.id)) return null;
  if (typeof candidate.name !== 'string') return null;
  const name = candidate.name.trim();
  if (!name || name.length > MAX_CUSTOM_ENGINE_NAME_LENGTH) return null;
  const urlTemplate = normalizeCustomEngineUrlTemplate(candidate.urlTemplate);
  if (!urlTemplate) return null;
  return { id: candidate.id, name, urlTemplate };
}

/**
 * Defensive storage normalization: invalid, repeated-id, and repeated-urlTemplate
 * records are discarded in first-seen order. Cap at MAX_CUSTOM_ENGINES.
 *
 * Trusted storage reads must never treat an oversized collection as empty — that
 * would let create/update/delete rewrite storage with a tiny array and wipe data.
 * Oversize-by-bytes still normalizes item-by-item; use isBoundedCustomEngineCollection
 * for untrusted import/config rejection.
 */
export function normalizeCustomEngineDefinitions(value: unknown): CustomEngineDefinition[] {
  if (!Array.isArray(value)) return [];
  const seen = new Set<CustomEngineId>();
  const seenUrls = new Set<string>();
  const definitions: CustomEngineDefinition[] = [];
  for (const item of value) {
    const definition = normalizeCustomEngineDefinition(item);
    if (!definition || seen.has(definition.id)) continue;
    if (seenUrls.has(definition.urlTemplate)) continue;
    seen.add(definition.id);
    seenUrls.add(definition.urlTemplate);
    definitions.push(definition);
    if (definitions.length >= MAX_CUSTOM_ENGINES) break;
  }
  return definitions;
}

/** Strict guard for untrusted import/config payloads (not trusted storage reads). */
export function isBoundedCustomEngineCollection(value: unknown): value is unknown[] {
  return Array.isArray(value) && value.length <= MAX_CUSTOM_ENGINES && serializedSize(value) <= MAX_CUSTOM_ENGINES_SERIALIZED_BYTES;
}

/** UTF-8 JSON byte length of a value; Infinity when stringify fails. */
export function customEnginesSerializedBytes(value: unknown): number {
  return serializedSize(value);
}

function serializedSize(value: unknown): number {
  try { return new TextEncoder().encode(JSON.stringify(value)).length; } catch { return Infinity; }
}

/** Builds the navigation URL by replacing `%s` with the encoded query. */
export function buildCustomEngineUrl(urlTemplate: string, query: string): string {
  return urlTemplate.replace('%s', encodeURIComponent(query));
}

/** Lists duplicate urlTemplate groups in normalized definitions. */
export function findDuplicateCustomEngineUrls(definitions: readonly CustomEngineDefinition[]): { urlTemplate: string; ids: CustomEngineId[] }[] {
  const groups = new Map<string, CustomEngineId[]>();
  for (const definition of definitions) {
    const ids = groups.get(definition.urlTemplate) ?? [];
    ids.push(definition.id);
    groups.set(definition.urlTemplate, ids);
  }
  return [...groups.entries()]
    .filter(([, ids]) => ids.length > 1)
    .map(([urlTemplate, ids]) => ({ urlTemplate, ids }));
}

/**
 * Validates a content-script-supplied URL for the background `openNewTab` handler.
 *
 * Accepts only `http:`/`https:` and rejects credentials, mirroring
 * normalizeCustomEngineUrlTemplate. Every other scheme (chrome:, chrome-extension:,
 * javascript:, data:, file:, view-source:, …) is rejected. Returns the parsed
 * `url.href` — the same serialization used for navigation, so validation and
 * tabs.create operate on one canonical form — or null on any parse failure,
 * rejection, or over-length input.
 */
export function sanitizeOpenNewTabUrl(raw: string): string | null {
  if (typeof raw !== 'string' || raw.length > MAX_CUSTOM_ENGINE_URL_LENGTH + 4096) return null;
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
  if (url.username || url.password) return null;
  return url.href;
}
