import type { ProviderId } from './providers/types';

/** IDs for user-defined, per-provider search source instances (`inst:<providerId>:<uuid>`). */
export type ProviderInstanceId = `inst:${ProviderId}:${string}`;

/** Persisted Provider Instance record. `options` are adapter-owned and schema-agnostic. */
export interface ProviderInstance {
  id: ProviderInstanceId;
  baseProviderId: ProviderId;
  name: string;
  options: Record<string, unknown>;
}

const INSTANCE_ID_PREFIX = 'inst:';
/** Stable, storage-safe ids generated by the worker (UUIDs satisfy this form). */
const INSTANCE_ID_TOKEN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;
/** Known base providers; keep in sync with the `ProviderId` union in `./providers/types`. */
const PROVIDER_IDS: ReadonlySet<ProviderId> = new Set<ProviderId>([
  'tavily', 'exa', 'brave', 'stepfun', 'stepfun-plan', 'jina', 'doubao', 'doubao-global',
]);

/**
 * Providers that ship a per-instance options form in the options UI. Only these are
 * offered in the base-provider dropdown when creating an instance — creating an
 * instance of a provider with no options would be meaningless (it would behave
 * identically to the bare provider pill).
 *
 * Phase 1: only Exa has an options schema. Extend this set to enable more providers;
 * each addition must also ship an options form in `ProviderInstanceManager` and an
 * options-builder branch in the create/update submit path.
 */
export const PROVIDERS_WITH_INSTANCE_OPTIONS: ReadonlySet<ProviderId> = new Set<ProviderId>([
  'exa',
]);

export const MAX_PROVIDER_INSTANCES = 50;
export const MAX_INSTANCE_NAME_LENGTH = 40;
// Leaves ample room below the 256 KiB complete-import limit for the rest of the
// config while still bounding a persisted collection read from storage.
export const MAX_INSTANCES_SERIALIZED_BYTES = 128 * 1024;

function isProviderId(value: string): value is ProviderId {
  return PROVIDER_IDS.has(value as ProviderId);
}

export function isProviderInstanceId(id: string): id is ProviderInstanceId {
  const parts = id.split(':');
  return parts.length === 3
    && parts[0] === INSTANCE_ID_PREFIX.slice(0, -1)
    && isProviderId(parts[1])
    && INSTANCE_ID_TOKEN.test(parts[2]);
}

/** Validates and canonicalizes an untrusted persisted Provider Instance record. */
export function normalizeProviderInstance(value: unknown): ProviderInstance | null {
  if (!value || typeof value !== 'object') return null;
  const candidate = value as Record<string, unknown>;
  if (typeof candidate.id !== 'string' || !isProviderInstanceId(candidate.id)
    || typeof candidate.baseProviderId !== 'string' || !isProviderId(candidate.baseProviderId)
    || typeof candidate.name !== 'string') return null;
  // The base provider embedded in the id must agree with the declared one.
  if (candidate.id.split(':')[1] !== candidate.baseProviderId) return null;
  const options = candidate.options;
  if (typeof options !== 'object' || options === null || Array.isArray(options)) return null;
  const name = candidate.name.trim();
  return name && name.length <= MAX_INSTANCE_NAME_LENGTH
    ? { id: candidate.id, baseProviderId: candidate.baseProviderId, name, options: options as Record<string, unknown> }
    : null;
}

/**
 * Defensive storage normalization: invalid and repeated-id records are discarded
 * in first-seen order. Cap at MAX_PROVIDER_INSTANCES.
 *
 * Trusted storage reads must never treat an oversized collection as empty — that
 * would let create/update/delete rewrite storage with a tiny array and wipe data.
 * Oversize-by-bytes still normalizes item-by-item; use isBoundedProviderInstanceCollection
 * for untrusted import/config rejection.
 */
export function normalizeProviderInstances(value: unknown): ProviderInstance[] {
  if (!Array.isArray(value)) return [];
  const seen = new Set<ProviderInstanceId>();
  const instances: ProviderInstance[] = [];
  for (const item of value) {
    const instance = normalizeProviderInstance(item);
    if (!instance || seen.has(instance.id)) continue;
    seen.add(instance.id);
    instances.push(instance);
    if (instances.length >= MAX_PROVIDER_INSTANCES) break;
  }
  return instances;
}

/** Strict guard for untrusted import/config payloads (not trusted storage reads). */
export function isBoundedProviderInstanceCollection(value: unknown): value is unknown[] {
  return Array.isArray(value) && value.length <= MAX_PROVIDER_INSTANCES && serializedSize(value) <= MAX_INSTANCES_SERIALIZED_BYTES;
}

/** UTF-8 JSON byte length of a value; Infinity when stringify fails. */
export function providerInstancesSerializedBytes(value: unknown): number {
  return serializedSize(value);
}

function serializedSize(value: unknown): number {
  try { return new TextEncoder().encode(JSON.stringify(value)).length; } catch { return Infinity; }
}
