import type { EngineId } from './engines/types';

/** IDs for user-defined, site-scoped search sources. */
export type SiteEngineId = `site:${string}`;

/** The engines which can express a site restriction. */
export type SiteEngineEngineId = Extract<EngineId, 'google' | 'bing' | 'baidu'>;

/** Persisted Site Engine record. `target` is always the normalized canonical URL. */
export interface SiteEngineDefinition {
  id: SiteEngineId;
  name: string;
  target: string;
  engineId: SiteEngineEngineId;
}

/** Parsed form of a normalized target. Consumers should use this rather than parsing `target`. */
export interface NormalizedSiteTarget {
  /** Full canonical HTTP(S) URL, without a query string or fragment. */
  canonicalUrl: string;
  hostname: string;
  pathname: string;
}

export interface SiteEngineQueryMatch {
  siteId: SiteEngineId;
  baseQuery: string;
}

export interface DuplicateSiteEngineScope {
  engineId: SiteEngineEngineId;
  scope: string;
  siteIds: SiteEngineId[];
}

const SITE_ID_PREFIX = 'site:';
/** Stable, storage-safe ids generated by the worker (UUIDs satisfy this form). */
const SITE_ID_TOKEN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;
const SITE_ENGINE_IDS: ReadonlySet<string> = new Set(['google', 'bing', 'baidu']);
export const MAX_SITE_ENGINES = 50;
export const MAX_SITE_ENGINE_NAME_LENGTH = 40;
export const MAX_SITE_TARGET_LENGTH = 2048;
// Leaves ample room below the 256 KiB complete-import limit for the rest of the
// config while still bounding a persisted collection read from storage.
export const MAX_SITE_ENGINES_SERIALIZED_BYTES = 128 * 1024;

export function isSiteEngineId(id: string): id is SiteEngineId {
  return id.startsWith(SITE_ID_PREFIX) && SITE_ID_TOKEN.test(id.slice(SITE_ID_PREFIX.length));
}

export function isSiteEngineEngineId(id: string): id is SiteEngineEngineId {
  return SITE_ENGINE_IDS.has(id);
}

/**
 * Converts an entered site target to a safe canonical URL. Only HTTP(S) targets
 * are supported; credentials are deliberately rejected rather than retained.
 */
export function normalizeSiteTarget(value: unknown): NormalizedSiteTarget | null {
  if (typeof value !== 'string') return null;
  const input = value.trim();
  if (!input || input.length > MAX_SITE_TARGET_LENGTH || /\s/.test(input)) return null;

  const hasScheme = /^[a-zA-Z][a-zA-Z\d+.-]*:\/\//.test(input);
  const hasUnsupportedScheme = /^[a-zA-Z][a-zA-Z\d+.-]*:/.test(input) && !hasScheme;
  const isHostWithPort = /^[^/?#\s]+:\d+(?:[/?#]|$)/.test(input);
  if (hasUnsupportedScheme && !isHostWithPort) return null;
  if (hasScheme && !/^https?:\/\//i.test(input)) return null;
  if (!hasScheme && input.startsWith('//')) return null;

  let url: URL;
  try {
    url = new URL(hasScheme ? input : `https://${input}`);
  } catch {
    return null;
  }
  if ((url.protocol !== 'http:' && url.protocol !== 'https:') || !url.hostname || url.username || url.password) {
    return null;
  }
  // Strip trailing FQDN dots so site: scopes and duplicate detection treat
  // `docs.example.com.` the same as `docs.example.com` (validation alone is not enough).
  const hostname = url.hostname.replace(/\.+$/, '').toLowerCase();
  if (!isPublicHostname(hostname)) return null;
  try {
    url.hostname = hostname;
  } catch {
    return null;
  }

  url.search = '';
  url.hash = '';
  if (url.href.length > MAX_SITE_TARGET_LENGTH) return null;
  return { canonicalUrl: url.href, hostname: url.hostname, pathname: url.pathname };
}

/** Reject targets that could disclose a private network name to a public engine. */
function isPublicHostname(hostname: string): boolean {
  // Site restrictions are sent to third-party search engines.  A DNS lookup
  // here would be racy and still allow DNS rebinding, so the safe allow-list is
  // public-looking DNS names only -- never an address literal.
  const host = hostname.toLowerCase().replace(/\.+$/, '');
  if (!host || host.includes(':') || /^\d+(?:\.\d+)+$/.test(host)) return false;
  const labels = host.split('.');
  if (labels.length < 2 || host.length > 253 || labels.some((label) => !/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label))) return false;

  const reservedSuffixes = ['localhost', 'local', 'internal', 'home', 'lan', 'test', 'invalid', 'example'];
  if (reservedSuffixes.some((suffix) => host === suffix || host.endsWith(`.${suffix}`))) return false;
  return host !== 'home.arpa' && !host.endsWith('.home.arpa');
}

/** Returns the engine-specific effective site scope for an already normalized target. */
export function siteScopeForTarget(engineId: SiteEngineEngineId, target: NormalizedSiteTarget): string {
  switch (engineId) {
    case 'google': {
      // Google `site:` operands must not embed a scheme. Host-only when the path
      // is empty/root; otherwise hostname + pathname (trailing slash stripped).
      const path = target.pathname.replace(/\/+$/, '');
      return path ? `${target.hostname}${path}` : target.hostname;
    }
    case 'bing': {
      const segments = target.pathname.split('/').filter(Boolean).slice(0, 2);
      return segments.length === 0 ? target.hostname : `${target.hostname}/${segments.join('/')}`;
    }
    case 'baidu':
      return target.hostname;
  }
}

/** Returns a definition's effective scope, or null when its persisted target is invalid. */
export function siteScopeForDefinition(definition: Pick<SiteEngineDefinition, 'engineId' | 'target'>): string | null {
  const target = normalizeSiteTarget(definition.target);
  return target ? siteScopeForTarget(definition.engineId, target) : null;
}

/** Validates and canonicalizes an untrusted persisted Site Engine record. */
export function normalizeSiteEngineDefinition(value: unknown): SiteEngineDefinition | null {
  if (!value || typeof value !== 'object') return null;
  const candidate = value as Record<string, unknown>;
  if (typeof candidate.id !== 'string' || !isSiteEngineId(candidate.id)
    || typeof candidate.name !== 'string'
    || typeof candidate.engineId !== 'string' || !isSiteEngineEngineId(candidate.engineId)) return null;
  const target = normalizeSiteTarget(candidate.target);
  const name = candidate.name.trim();
  return target && name && name.length <= MAX_SITE_ENGINE_NAME_LENGTH
    ? { id: candidate.id, name, target: target.canonicalUrl, engineId: candidate.engineId }
    : null;
}

/**
 * Defensive storage normalization: invalid, repeated-id, and repeated-effective-scope
 * records are discarded in first-seen order. Cap at MAX_SITE_ENGINES.
 *
 * Trusted storage reads must never treat an oversized collection as empty — that
 * would let create/update/delete rewrite storage with a tiny array and wipe data.
 * Oversize-by-bytes still normalizes item-by-item; use isBoundedSiteEngineCollection
 * for untrusted import/config rejection.
 */
export function normalizeSiteEngineDefinitions(value: unknown): SiteEngineDefinition[] {
  if (!Array.isArray(value)) return [];
  const seen = new Set<SiteEngineId>();
  const seenScopes = new Set<string>();
  const definitions: SiteEngineDefinition[] = [];
  for (const item of value) {
    const definition = normalizeSiteEngineDefinition(item);
    if (!definition || seen.has(definition.id)) continue;
    const scope = siteScopeForDefinition(definition);
    if (!scope || seenScopes.has(`${definition.engineId}\u0000${scope}`)) continue;
    seen.add(definition.id);
    seenScopes.add(`${definition.engineId}\u0000${scope}`);
    definitions.push(definition);
    if (definitions.length >= MAX_SITE_ENGINES) break;
  }
  return definitions;
}

/** Strict guard for untrusted import/config payloads (not trusted storage reads). */
export function isBoundedSiteEngineCollection(value: unknown): value is unknown[] {
  return Array.isArray(value) && value.length <= MAX_SITE_ENGINES && serializedSize(value) <= MAX_SITE_ENGINES_SERIALIZED_BYTES;
}

/** UTF-8 JSON byte length of a value; Infinity when stringify fails. */
export function siteEnginesSerializedBytes(value: unknown): number {
  return serializedSize(value);
}

function serializedSize(value: unknown): number {
  try { return new TextEncoder().encode(JSON.stringify(value)).length; } catch { return Infinity; }
}

/** Builds the query sent to the selected search engine. */
export function buildSiteEngineQuery(definition: Pick<SiteEngineDefinition, 'engineId' | 'target'>, baseQuery: string): string | null {
  const scope = siteScopeForDefinition(definition);
  if (!scope) return null;
  return `site:${scope}${baseQuery ? ` ${baseQuery}` : ''}`;
}

/**
 * Finds the saved definition that generated a query and returns the original
 * base query. A prefix only matches when it is complete or followed by exactly
 * the generated separating space, preventing partial-scope stripping.
 */
export function matchSiteEngineQuery(
  engineId: SiteEngineEngineId,
  query: string,
  definitions: readonly SiteEngineDefinition[],
  activeSourceId?: string | null,
  sourceOrder?: readonly string[],
): SiteEngineQueryMatch | null {
  const valid = definitions.flatMap((definition) => {
    if (definition.engineId !== engineId) return [];
    const prefix = buildSiteEngineQuery(definition, '');
    return prefix ? [{ definition, prefix }] : [];
  });
  const byId = new Map(valid.map((entry) => [entry.definition.id, entry]));
  const ordered: typeof valid = [];
  const orderedIds = new Set<SiteEngineId>();
  const add = (id: string | null | undefined) => {
    const entry = id ? byId.get(id as SiteEngineId) : undefined;
    if (entry && !orderedIds.has(entry.definition.id)) {
      orderedIds.add(entry.definition.id);
      ordered.push(entry);
    }
  };
  add(activeSourceId);
  for (const id of sourceOrder ?? []) add(id);
  for (const entry of valid) add(entry.definition.id);

  for (const { definition, prefix } of ordered) {
    if (query === prefix) return { siteId: definition.id, baseQuery: '' };
    if (query.startsWith(`${prefix} `)) return { siteId: definition.id, baseQuery: query.slice(prefix.length + 1) };
  }
  return null;
}

/** Lists duplicate effective (engine, scope) pairs in normalized definitions. */
export function findDuplicateSiteEngineScopes(definitions: readonly SiteEngineDefinition[]): DuplicateSiteEngineScope[] {
  const groups = new Map<string, DuplicateSiteEngineScope>();
  for (const definition of definitions) {
    const scope = siteScopeForDefinition(definition);
    if (!scope) continue;
    const key = `${definition.engineId}\u0000${scope}`;
    const group = groups.get(key) ?? { engineId: definition.engineId, scope, siteIds: [] };
    group.siteIds.push(definition.id);
    groups.set(key, group);
  }
  return [...groups.values()].filter((group) => group.siteIds.length > 1);
}
